import { Language, MarketplaceCategory, Product, GovernmentScheme } from './types';

export const INDIAN_STATES = [
    "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", 
    "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka",
    "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram",
    "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana",
    "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"
];

export const MOCK_PRODUCTS: Product[] = [
    { id: '1', category: MarketplaceCategory.Crops, name: 'Wheat', image: 'https://images.unsplash.com/photo-1507633698035-83f645a335a4?q=80&w=300&h=200&fit=crop', price: 20, unit: 'kg', quantity: 500 },
    { id: '2', category: MarketplaceCategory.Crops, name: 'Rice', image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?q=80&w=300&h=200&fit=crop', price: 40, unit: 'kg', quantity: 1000 },
    { id: '3', category: MarketplaceCategory.Machineries, name: 'Tractor', image: 'https://images.unsplash.com/photo-1598586958312-6152431478fb?q=80&w=300&h=200&fit=crop', price: 500, unit: 'hour', sellOrRent: 'rent' },
    { id: '4', category: MarketplaceCategory.Machineries, name: 'Harvester', image: 'https://images.unsplash.com/photo-1627920769854-d873812e9b8f?q=80&w=300&h=200&fit=crop', price: 1500000, unit: 'fixed', sellOrRent: 'sell' },
    { id: '5', category: MarketplaceCategory.Chemicals, name: 'Pesticide A', image: 'https://images.unsplash.com/photo-1621379921617-b671a5c0b115?q=80&w=300&h=200&fit=crop', price: 800, unit: 'litre', quantity: 100, expiryDate: '2025-12-31' },
    { id: '6', category: MarketplaceCategory.Fertilizers, name: 'Urea', image: 'https://images.unsplash.com/photo-1604942555986-e0f8f828751b?q=80&w=300&h=200&fit=crop', price: 30, unit: 'kg', quantity: 2000 },
];

export const MOCK_SCHEMES: GovernmentScheme[] = [
    {
        id: '1',
        title: {
            [Language.EN]: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
            [Language.HI]: 'प्रधान मंत्री किसान सम्मान निधि (पीएम-किसान)',
            [Language.MR]: 'प्रधानमंत्री किसान सन्मान निधी (पीएम-किसान)',
        },
        description: {
            [Language.EN]: 'An income support scheme for all landholding farmer families.',
            [Language.HI]: 'सभी भूमिधारक किसान परिवारों के लिए एक आय सहायता योजना।',
            [Language.MR]: 'सर्व भूधारक शेतकरी कुटुंबांसाठी उत्पन्न समर्थन योजना.',
        },
        eligibility: {
            [Language.EN]: 'All landholding farmer families.',
            [Language.HI]: 'सभी भूमिधारक किसान परिवार।',
            [Language.MR]: 'सर्व भूधारक शेतकरी कुटुंबे.',
        },
        benefits: {
            [Language.EN]: '₹6,000 per year in three equal installments.',
            [Language.HI]: 'तीन समान किश्तों में प्रति वर्ष ₹6,000।',
            [Language.MR]: 'तीन समान हप्त्यांमध्ये प्रतिवर्षी ₹6,000.',
        },
        link: 'https://pmkisan.gov.in/',
    },
    {
        id: '2',
        title: {
            [Language.EN]: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
            [Language.HI]: 'प्रधानमंत्री फसल बीमा योजना (पीएमएफबीवाई)',
            [Language.MR]: 'प्रधानमंत्री फसल विमा योजना (पीएमएफबीवाय)',
        },
        description: {
            [Language.EN]: 'A crop insurance scheme to provide financial support to farmers suffering crop loss/damage.',
            [Language.HI]: 'फसल हानि/क्षति से पीड़ित किसानों को वित्तीय सहायता प्रदान करने के लिए एक फसल बीमा योजना।',
            [Language.MR]: 'पीक नुकसान/हानी झालेल्या शेतकऱ्यांना आर्थिक सहाय्य देण्यासाठी पीक विमा योजना.',
        },
        eligibility: {
            [Language.EN]: 'All farmers including sharecroppers and tenant farmers growing notified crops in notified areas.',
            [Language.HI]: 'अधिसूचित क्षेत्रों में अधिसूचित फसलें उगाने वाले बटाईदार और किरायेदार किसानों सहित सभी किसान।',
            [Language.MR]: 'अधिसूचित क्षेत्रांमध्ये अधिसूचित पिके घेणारे वाटेकरी आणि भाडेकरू शेतकऱ्यांसह सर्व शेतकरी.',
        },
        benefits: {
            [Language.EN]: 'Insurance coverage against crop failure.',
            [Language.HI]: 'फसल की विफलता के खिलाफ बीमा कवरेज।',
            [Language.MR]: 'पीक अपयशाविरुद्ध विमा संरक्षण.',
        },
        link: 'https://pmfby.gov.in/',
    },
];

export const TEXTS: { [lang in Language]: { [key: string]: string } } = {
    [Language.EN]: {
        'appName': 'AgriPredict',
        'welcome': 'Welcome',
        'logout': 'Logout',
        'cropDiseaseDetection': 'Crop Disease Detection',
        'marketplace': 'Marketplace',
        'govtSchemes': 'Government Schemes',
        'waterMonitor': 'Water Level Monitor',
        'loginTitle': 'Login to AgriPredict',
        'registerTitle': 'Create an Account',
        'username': 'Username',
        'email': 'Email / Phone',
        'password': 'Password',
        'confirmPassword': 'Confirm Password',
        'region': 'Region',
        'state': 'State',
        'city': 'City',
        'login': 'Login',
        'register': 'Register',
        'noAccount': "Don't have an account?",
        'haveAccount': 'Already have an account?',
        'signUp': 'Sign Up',
        'signIn': 'Sign In',
        'uploadImage': 'Upload or Capture Plant Image',
        'capture': 'Capture with Camera',
        'upload': 'Upload from Gallery',
        'detecting': 'Detecting Disease...',
        'diseaseResult': 'Detection Result',
        'diseaseName': 'Disease Name',
        'recommendedSolution': 'Recommended Solution',
        'chatWithBot': 'Chat with AgriBot for help',
        'chatPlaceholder': 'Ask about treatment...',
        'send': 'Send',
        'buy': 'Buy',
        'sell': 'Sell',
        'rent': 'Rent',
        'searchProducts': 'Search for products...',
        'sellYourProduct': 'Sell Your Product',
        'category': 'Category',
        'productName': 'Product Name',
        'quantity': 'Quantity',
        'price': 'Price',
        'image': 'Image',
        'expiryDate': 'Expiry Date',
        'sellOrRent': 'Action',
        'postAd': 'Post Advertisement',
        'productUploaded': 'Product uploaded successfully!',
        'searchSchemes': 'Search for schemes...',
        'eligibility': 'Eligibility',
        'benefits': 'Benefits',
        'officialLink': 'Official Link',
        'soilMoisture': 'Live Soil Moisture Level',
        'goodMoisture': 'Soil moisture is optimal. No irrigation needed.',
        'lowMoisture': 'Soil is dry. It is recommended to start irrigation.',
        'highMoisture': 'Soil is too wet. Stop irrigation to avoid waterlogging.',
        'fetchingData': 'Fetching live data...',
        'selectCategory': 'Select a Category',
        'crops': 'Crops',
        'machineries': 'Machineries',
        'chemicals': 'Chemicals',
        'fertilizers': 'Fertilizers',
        'perKg': 'per kg',
        'perLitre': 'per litre',
        'perHour': 'per hour',
        'fixedPrice': 'Fixed Price',
    },
    [Language.HI]: {
        'appName': 'एग्रीप्रेडिक्ट',
        'welcome': 'स्वागत है',
        'logout': 'लॉग आउट',
        'cropDiseaseDetection': 'फसल रोग का पता लगाना',
        'marketplace': 'बाजार',
        'govtSchemes': 'सरकारी योजनाएं',
        'waterMonitor': 'जल स्तर की निगरानी',
        'loginTitle': 'एग्रीप्रेडिक्ट में लॉगिन करें',
        'registerTitle': 'खाता बनाएं',
        'username': 'उपयोगकर्ता नाम',
        'email': 'ईमेल/फोन',
        'password': 'पासवर्ड',
        'confirmPassword': 'पासवर्ड की पुष्टि करें',
        'region': 'क्षेत्र',
        'state': 'राज्य',
        'city': 'शहर',
        'login': 'लॉग इन करें',
        'register': 'पंजीकरण करें',
        'noAccount': 'खाता नहीं है?',
        'haveAccount': 'पहले से ही एक खाता है?',
        'signUp': 'साइन अप करें',
        'signIn': 'साइन इन करें',
        'uploadImage': 'पौधे की तस्वीर अपलोड या कैप्चर करें',
        'capture': 'कैमरे से कैप्चर करें',
        'upload': 'गैलरी से अपलोड करें',
        'detecting': 'रोग का पता लगाया जा रहा है...',
        'diseaseResult': 'पहचान का परिणाम',
        'diseaseName': 'रोग का नाम',
        'recommendedSolution': 'अनुशंसित समाधान',
        'chatWithBot': 'सहायता के लिए एग्रीबॉट से चैट करें',
        'chatPlaceholder': 'उपचार के बारे में पूछें...',
        'send': 'भेजें',
        'buy': 'खरीदें',
        'sell': 'बेचें',
        'rent': 'किराए पर दें',
        'searchProducts': 'उत्पादों की खोज करें...',
        'sellYourProduct': 'अपना उत्पाद बेचें',
        'category': 'श्रेणी',
        'productName': 'उत्पाद का नाम',
        'quantity': 'मात्रा',
        'price': 'कीमत',
        'image': 'छवि',
        'expiryDate': 'समाप्ति तिथि',
        'sellOrRent': 'कार्रवाई',
        'postAd': 'विज्ञापन पोस्ट करें',
        'productUploaded': 'उत्पाद सफलतापूर्वक अपलोड किया गया!',
        'searchSchemes': 'योजनाओं की खोज करें...',
        'eligibility': 'पात्रता',
        'benefits': 'लाभ',
        'officialLink': 'आधिकारिक लिंक',
        'soilMoisture': 'लाइव मिट्टी की नमी का स्तर',
        'goodMoisture': 'मिट्टी की नमी इष्टतम है। सिंचाई की आवश्यकता नहीं है।',
        'lowMoisture': 'मिट्टी सूखी है। सिंचाई शुरू करने की सिफारिश की जाती है।',
        'highMoisture': 'मिट्टी बहुत गीली है। जलभराव से बचने के लिए सिंचाई बंद कर दें।',
        'fetchingData': 'लाइव डेटा प्राप्त हो रहा है...',
        'selectCategory': 'एक श्रेणी चुनें',
        'crops': 'फसलें',
        'machineries': 'मशीनरी',
        'chemicals': 'रसायन',
        'fertilizers': 'उर्वरक',
        'perKg': 'प्रति किलो',
        'perLitre': 'प्रति लीटर',
        'perHour': 'प्रति घंटा',
        'fixedPrice': 'निश्चित मूल्य',
    },
    [Language.MR]: {
        'appName': 'ऍग्रीप्रेडिक्ट',
        'welcome': 'स्वागत आहे',
        'logout': 'लॉग आउट',
        'cropDiseaseDetection': 'पीक रोग ओळख',
        'marketplace': 'बाजारपेठ',
        'govtSchemes': 'सरकारी योजना',
        'waterMonitor': 'पाणी पातळी निरीक्षण',
        'loginTitle': 'ऍग्रीप्रेडिक्टमध्ये लॉग इन करा',
        'registerTitle': 'खाते तयार करा',
        'username': 'वापरकर्तानाव',
        'email': 'ईमेल/फोन',
        'password': 'पासवर्ड',
        'confirmPassword': 'पासवर्डची पुष्टी करा',
        'region': 'प्रदेश',
        'state': 'राज्य',
        'city': 'शहर',
        'login': 'लॉग इन करा',
        'register': 'नोंदणी करा',
        'noAccount': 'खाते नाही?',
        'haveAccount': 'आधीपासूनच खाते आहे?',
        'signUp': 'साइन अप करा',
        'signIn': 'साइन इन करा',
        'uploadImage': 'वनस्पतीचे छायाचित्र अपलोड किंवा कॅप्चर करा',
        'capture': 'कॅमेऱ्याने कॅप्चर करा',
        'upload': 'गॅलरीमधून अपलोड करा',
        'detecting': 'रोगाचे निदान होत आहे...',
        'diseaseResult': 'निदान परिणाम',
        'diseaseName': 'रोगाचे नाव',
        'recommendedSolution': 'शिफारस केलेला उपाय',
        'chatWithBot': 'मदतीसाठी ऍग्रीबॉटशी चॅट करा',
        'chatPlaceholder': 'उपचाराबद्दल विचारा...',
        'send': 'पाठवा',
        'buy': 'खरेदी करा',
        'sell': 'विक्री करा',
        'rent': 'भाड्याने द्या',
        'searchProducts': 'उत्पादनांसाठी शोधा...',
        'sellYourProduct': 'तुमचे उत्पादन विका',
        'category': 'श्रेणी',
        'productName': 'उत्पादनाचे नाव',
        'quantity': 'प्रमाण',
        'price': 'किंमत',
        'image': 'प्रतिमा',
        'expiryDate': 'समाप्तीची तारीख',
        'sellOrRent': 'कृती',
        'postAd': 'जाहिरात पोस्ट करा',
        'productUploaded': 'उत्पादन यशस्वीरित्या अपलोड झाले!',
        'searchSchemes': 'योजनांसाठी शोधा...',
        'eligibility': 'पात्रता',
        'benefits': 'फायदे',
        'officialLink': 'अधिकृत दुवा',
        'soilMoisture': 'थेट जमिनीतील ओलावा पातळी',
        'goodMoisture': 'जमिनीतील ओलावा चांगला आहे. सिंचनाची गरज नाही.',
        'lowMoisture': 'जमीन कोरडी आहे. सिंचन सुरू करण्याची शिफारस केली जाते.',
        'highMoisture': 'जमीन खूप ओली आहे. पाणी साचू नये म्हणून सिंचन थांबवा.',
        'fetchingData': 'थेट डेटा आणत आहे...',
        'selectCategory': 'एक श्रेणी निवडा',
        'crops': 'पिके',
        'machineries': 'यंत्रसामग्री',
        'chemicals': 'रसायने',
        'fertilizers': 'खते',
        'perKg': 'प्रति किलो',
        'perLitre': 'प्रति लिटर',
        'perHour': 'प्रति तास',
        'fixedPrice': 'निश्चित किंमत',
    }
};